name: Build QMK From JSON

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install QMK CLI
        run: |
          pip install qmk
          qmk setup -y

      - name: Compile firmware from JSON
        run: qmk compile keyboards/silakka54/keyboard.json

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: silakka54-uf2
          path: |
            *.uf2
            .build/*.uf2
